all:
  vars:
    ansible_connection: ssh
    ansible_user: client
    ansible_become: true
    ansible_ssh_private_key_file: /home/hari/.ssh/id_ed25519
zookeeper:
  hosts:
    192.168.56.102:

kafka_broker:
  hosts:
    192.168.56.102:
      broker_id: 0
