---

- hosts: client
  become: true
  gather_facts: true
  tasks:
  
  - name: install apache2 and php packages,update repository index
    tags: install
    apt:
      name:
      - "{{ apache_package }}"
      - libapache2-mod-php
      state: latest
      update_cache: yes 
