  - name: copy default html file
    tags: install
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode:  0644
      
  - name: install apache2 and php packages,update repository index
    tags: install
    apt:
      name:
      - "{{ apache_package }}"
      - libapache2-mod-php
      state: latest
      update_cache: yes
      
  - name: change timeout settingsin apache conf file
    tags: install
    lineinfile:
      path: /etc/apache2/apache2.conf
      regexp: '^Timeout'
      line: Timeout 305
    register: apache_change
    
  - name: restart apache2
    tags: install
    service:
      name: apache2
      state: restarted
    when: apache_change.changed
